prometheus:
  enabled: true
  prometheusSpec:
    ignoreNamespaceSelectors: false  # Default or required value
  server:
    global:
      scrape_interval: 15s
    persistentVolume:
      enabled: true
      size: 10Gi

grafana:
  enabled: true
  adminPassword: "your-secure-password"
  service:
    type: LoadBalancer
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
